AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Crawl customer news
Parameters:
  ProjectName:
    Description: News feed handler
    Type: String
    Default: News feed handler
  Account:
    Description: AWS AccountNumber
    Type: Number

Resources:
  GetNewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getNews
      Handler: feedStarter.getNews
      Runtime: python3.6
      CodeUri: ./
      Role: !Sub arn:aws:iam::${Account}:role/lambda-nfh
      Timeout: 900
  GetNewsPerProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getNewsPerProfile
      Handler: feedHandler.getNewsPerProfile
      Runtime: python3.6
      CodeUri: ./
      Role: !Sub arn:aws:iam::${Account}:role/lambda-nfh
      Timeout: 900
